[MeasureAudioCalc1]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio1))'
UpdateDivider=1
[MeasureAudioCalc2]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio2))'
UpdateDivider=1
[MeasureAudioCalc3]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio3))'
UpdateDivider=1
[MeasureAudioCalc4]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio4))'
UpdateDivider=1
[MeasureAudioCalc5]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio5))'
UpdateDivider=1
[MeasureAudioCalc6]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio6))'
UpdateDivider=1
[MeasureAudioCalc7]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio7))'
UpdateDivider=1
[MeasureAudioCalc8]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio8))'
UpdateDivider=1
[MeasureAudioCalc9]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio9))'
UpdateDivider=1
[MeasureAudioCalc10]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio10))'
UpdateDivider=1
[MeasureAudioCalc11]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio11))'
UpdateDivider=1
[MeasureAudioCalc12]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio12))'
UpdateDivider=1
[MeasureAudioCalc13]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio13))'
UpdateDivider=1
[MeasureAudioCalc14]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio14))'
UpdateDivider=1
[MeasureAudioCalc15]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio15))'
UpdateDivider=1
[MeasureAudioCalc16]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio16))'
UpdateDivider=1
[MeasureAudioCalc17]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio17))'
UpdateDivider=1
[MeasureAudioCalc18]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio18))'
UpdateDivider=1
[MeasureAudioCalc19]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio19))'
UpdateDivider=1
[MeasureAudioCalc20]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio20))'
UpdateDivider=1
[MeasureAudioCalc21]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio21))'
UpdateDivider=1
[MeasureAudioCalc22]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio22))'
UpdateDivider=1
[MeasureAudioCalc23]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio23))'
UpdateDivider=1
[MeasureAudioCalc24]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio24))'
UpdateDivider=1
[MeasureAudioCalc25]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio25))'
UpdateDivider=1
[MeasureAudioCalc26]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio26))'
UpdateDivider=1
[MeasureAudioCalc27]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio27))'
UpdateDivider=1
[MeasureAudioCalc28]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio28))'
UpdateDivider=1
[MeasureAudioCalc29]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio29))'
UpdateDivider=1
[MeasureAudioCalc30]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio30))'
UpdateDivider=1
[MeasureAudioCalc31]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio31))'
UpdateDivider=1
[MeasureAudioCalc32]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio32))'
UpdateDivider=1
[MeasureAudioCalc33]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio33))'
UpdateDivider=1
[MeasureAudioCalc34]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio34))'
UpdateDivider=1
[MeasureAudioCalc35]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio35))'
UpdateDivider=1
[MeasureAudioCalc36]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio36))'
UpdateDivider=1
[MeasureAudioCalc37]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio37))'
UpdateDivider=1
[MeasureAudioCalc38]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio38))'
UpdateDivider=1
[MeasureAudioCalc39]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio39))'
UpdateDivider=1
[MeasureAudioCalc40]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio40))'
UpdateDivider=1
[MeasureAudioCalc41]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio41))'
UpdateDivider=1
[MeasureAudioCalc42]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio42))'
UpdateDivider=1
[MeasureAudioCalc43]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio43))'
UpdateDivider=1
[MeasureAudioCalc44]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio44))'
UpdateDivider=1
[MeasureAudioCalc45]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio45))'
UpdateDivider=1
[MeasureAudioCalc46]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio46))'
UpdateDivider=1
[MeasureAudioCalc47]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio47))'
UpdateDivider=1
[MeasureAudioCalc48]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio48))'
UpdateDivider=1
[MeasureAudioCalc49]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio49))'
UpdateDivider=1
[MeasureAudioCalc50]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio50))'
UpdateDivider=1
[MeasureAudioCalc51]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio51))'
UpdateDivider=1
[MeasureAudioCalc52]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio52))'
UpdateDivider=1
[MeasureAudioCalc53]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio53))'
UpdateDivider=1
[MeasureAudioCalc54]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio54))'
UpdateDivider=1
[MeasureAudioCalc55]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio55))'
UpdateDivider=1
[MeasureAudioCalc56]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio56))'
UpdateDivider=1
[MeasureAudioCalc57]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio57))'
UpdateDivider=1
[MeasureAudioCalc58]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio58))'
UpdateDivider=1
[MeasureAudioCalc59]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio59))'
UpdateDivider=1
[MeasureAudioCalc60]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio60))'
UpdateDivider=1
[MeasureAudioCalc61]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio61))'
UpdateDivider=1
[MeasureAudioCalc62]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio62))'
UpdateDivider=1
[MeasureAudioCalc63]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio63))'
UpdateDivider=1
[MeasureAudioCalc64]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio64))'
UpdateDivider=1
[MeasureAudioCalc65]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio65))'
UpdateDivider=1
[MeasureAudioCalc66]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio66))'
UpdateDivider=1
[MeasureAudioCalc67]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio67))'
UpdateDivider=1
[MeasureAudioCalc68]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio68))'
UpdateDivider=1
[MeasureAudioCalc69]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio69))'
UpdateDivider=1
[MeasureAudioCalc70]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio70))'
UpdateDivider=1
[MeasureAudioCalc71]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio71))'
UpdateDivider=1
[MeasureAudioCalc72]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio72))'
UpdateDivider=1
[MeasureAudioCalc73]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio73))'
UpdateDivider=1
[MeasureAudioCalc74]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio74))'
UpdateDivider=1
[MeasureAudioCalc75]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio75))'
UpdateDivider=1
[MeasureAudioCalc76]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio76))'
UpdateDivider=1
[MeasureAudioCalc77]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio77))'
UpdateDivider=1
[MeasureAudioCalc78]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio78))'
UpdateDivider=1
[MeasureAudioCalc79]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio79))'
UpdateDivider=1
[MeasureAudioCalc80]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio80))'
UpdateDivider=1
[MeasureAudioCalc81]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio81))'
UpdateDivider=1
[MeasureAudioCalc82]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio82))'
UpdateDivider=1
[MeasureAudioCalc83]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio83))'
UpdateDivider=1
[MeasureAudioCalc84]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio84))'
UpdateDivider=1
[MeasureAudioCalc85]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio85))'
UpdateDivider=1
[MeasureAudioCalc86]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio86))'
UpdateDivider=1
[MeasureAudioCalc87]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio87))'
UpdateDivider=1
[MeasureAudioCalc88]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio88))'
UpdateDivider=1
[MeasureAudioCalc89]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio89))'
UpdateDivider=1
[MeasureAudioCalc90]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio90))'
UpdateDivider=1
[MeasureAudioCalc91]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio91))'
UpdateDivider=1
[MeasureAudioCalc92]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio92))'
UpdateDivider=1
[MeasureAudioCalc93]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio93))'
UpdateDivider=1
[MeasureAudioCalc94]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio94))'
UpdateDivider=1
[MeasureAudioCalc95]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio95))'
UpdateDivider=1
[MeasureAudioCalc96]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio96))'
UpdateDivider=1
[MeasureAudioCalc97]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio97))'
UpdateDivider=1
[MeasureAudioCalc98]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio98))'
UpdateDivider=1
[MeasureAudioCalc99]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio99))'
UpdateDivider=1
[MeasureAudioCalc100]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio100))'
UpdateDivider=1
[MeasureAudioCalc101]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio101))'
UpdateDivider=1
[MeasureAudioCalc102]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio102))'
UpdateDivider=1
[MeasureAudioCalc103]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio103))'
UpdateDivider=1
[MeasureAudioCalc104]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio104))'
UpdateDivider=1
[MeasureAudioCalc105]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio105))'
UpdateDivider=1
[MeasureAudioCalc106]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio106))'
UpdateDivider=1
[MeasureAudioCalc107]
Measure=Calc
Group=AudioCalc
Formula='(Max(0.01001, MeasureAudio107))'
UpdateDivider=1
